"""Seed specs (Korean legal content) — hand-authored by researcher2.

Each entry is a compact dict; `build_seeds.py` expands it into a full
messages-array sample and writes data/seeds/<Lane>.json.
"""
from __future__ import annotations

# Every L01 spec: (user_question, elements[list], facts[list], matching{element:bool}, mode, assistant_explanation)
L01_SPECS = [
    # 절도 계열
    ("피고인이 편의점에서 음료수 2캔을 주머니에 넣고 결제 없이 나왔다. 절도죄가 성립하는가?",
     ["타인의 재물", "절취", "불법영득의사"],
     ["편의점 소유 음료수 2캔", "주머니에 넣고 퇴장→점유이전", "결제의사 없음"],
     {"타인의 재물": True, "절취": True, "불법영득의사": True}, "and",
     "절도죄(형법 제329조)의 구성요건이 모두 충족되어 성립합니다."),
    ("A는 자신이 분실했다고 생각한 우산이 사실 B의 것임을 알면서 가져갔다. 절도죄 성립?",
     ["타인의 재물", "절취", "불법영득의사"],
     ["B 소유 우산", "A가 가져감", "A가 타인 소유임을 알고 있었음"],
     {"타인의 재물": True, "절취": True, "불법영득의사": True}, "and",
     "타인의 재물에 대한 불법영득의사가 있어 절도죄가 성립합니다."),
    ("자신의 자전거를 실수로 가져온 경우 절도죄?",
     ["타인의 재물", "절취", "불법영득의사"],
     ["자신 소유 자전거", "가져감", "불법영득의사 없음"],
     {"타인의 재물": False, "절취": False, "불법영득의사": False}, "and",
     "타인의 재물성 자체가 없어 절도죄가 성립하지 않습니다."),
    ("A는 B의 지갑을 잠시 보려고 들었다가 그대로 가지고 집에 갔다. 절도 성립?",
     ["타인의 재물", "절취", "불법영격의사"],
     ["B의 지갑", "가지고 귀가", "불법영득의사 인정"],
     {"타인의 재물": True, "절취": True, "불법영격의사": True}, "and",
     "점유이전과 불법영득의사로 절도죄 성립."),
    ("주운 지갑을 경찰에 신고하지 않고 현금만 꺼낸 경우의 구성요건?",
     ["타인의 재물", "횡령행위", "불법영득의사"],
     ["점유이탈물인 현금", "꺼내어 소비", "반환의사 없음"],
     {"타인의 재물": True, "횡령행위": True, "불법영득의사": True}, "and",
     "점유이탈물횡령죄의 구성요건을 충족합니다."),

    # 사기 계열
    ("A가 허위 투자상품을 설명하고 B로부터 1천만원을 송금받았다. 사기죄 성립?",
     ["기망행위", "착오", "처분행위", "재산상 이득"],
     ["허위 투자상품 설명", "B의 착오", "송금", "A의 1천만원 수령"],
     {"기망행위": True, "착오": True, "처분행위": True, "재산상 이득": True}, "and",
     "사기죄(형법 제347조)의 4요건 모두 충족."),
    ("A가 사실을 있는 그대로 말했는데 B가 혼자 오해하여 돈을 보낸 경우?",
     ["기망행위", "착오", "처분행위", "재산상 이득"],
     ["진실 고지", "B의 자의적 오해", "송금", "이득 발생"],
     {"기망행위": False, "착오": True, "처분행위": True, "재산상 이득": True}, "and",
     "기망행위가 없으므로 사기죄 불성립."),
    ("부작위에 의한 기망이 성립하는 경우(고지의무 위반)의 구성요건 충족 여부?",
     ["기망행위", "착오", "처분행위", "재산상 이득"],
     ["고지의무 있음에도 은폐", "상대방의 착오", "처분", "재산이득"],
     {"기망행위": True, "착오": True, "처분행위": True, "재산상 이득": True}, "and",
     "부작위 기망도 사기 성립."),
    ("A가 B에게 거짓 질병을 말했으나 B는 전혀 믿지 않고 돈을 주지 않았다.",
     ["기망행위", "착오", "처분행위", "재산상 이득"],
     ["거짓말", "B 불신", "처분 없음", "이득 없음"],
     {"기망행위": True, "착오": False, "처분행위": False, "재산상 이득": False}, "and",
     "착오·처분·이득이 없어 기수 불성립(미수 검토)."),
    ("컴퓨터에 허위정보를 입력해 타인 계좌에서 이체받은 경우의 요건은?",
     ["허위정보 입력", "정보처리", "재산상 이익"],
     ["은행 전산망에 허위 입력", "자동 처리", "자금 이체"],
     {"허위정보 입력": True, "정보처리": True, "재산상 이익": True}, "and",
     "컴퓨터등사용사기죄(347조의2) 성립."),

    # 폭행/상해
    ("A가 B의 멱살을 잡고 흔든 경우 폭행죄 성립?",
     ["유형력 행사", "사람의 신체에 대해"],
     ["멱살을 잡아 흔듦", "피해자 B의 신체"],
     {"유형력 행사": True, "사람의 신체에 대해": True}, "and",
     "폭행죄(형법 제260조) 구성요건 충족."),
    ("A가 공포심을 줄 목적으로 B의 면전에서 벽을 세게 친 경우?",
     ["유형력 행사", "사람의 신체에 대해"],
     ["벽을 때림", "신체 직접 접촉 없음"],
     {"유형력 행사": True, "사람의 신체에 대해": False}, "and",
     "판례상 신체에 대한 유형력 행사로 폭행 성립 가능(본 스키마에서는 엄격히 부정)."),
    ("A가 밀쳐서 B가 넘어지며 팔이 골절됨. 상해죄 성립?",
     ["폭행", "상해결과", "인과관계"],
     ["밀침", "팔 골절", "넘어짐과 골절 간 연결"],
     {"폭행": True, "상해결과": True, "인과관계": True}, "and",
     "상해죄(257조) 성립."),
    ("A가 B에게 욕설만 한 경우 폭행죄?",
     ["유형력 행사", "사람의 신체에 대해"],
     ["욕설", "신체접촉 없음"],
     {"유형력 행사": False, "사람의 신체에 대해": True}, "and",
     "유형력이 없어 폭행 불성립, 모욕죄 검토."),
    ("싸움 중 서로 때린 경우 쌍방 폭행의 구성요건?",
     ["유형력 행사", "사람의 신체에 대해"],
     ["A→B 타격", "B→A 타격"],
     {"유형력 행사": True, "사람의 신체에 대해": True}, "and",
     "쌍방 폭행죄 각각 성립."),

    # 배임/횡령
    ("회사 자금을 개인 용도로 사용한 경우 업무상 횡령?",
     ["타인 재물 보관자", "업무상 임무", "횡령행위"],
     ["회사 자금 관리자", "경리 업무", "개인 사용"],
     {"타인 재물 보관자": True, "업무상 임무": True, "횡령행위": True}, "and",
     "업무상 횡령죄(356조) 성립."),
    ("타인의 사무를 처리하는 자가 임무에 위배하여 재산상 손해를 가한 경우 배임?",
     ["타인 사무 처리자", "임무위배", "재산상 손해", "고의"],
     ["신임관계", "이사의 자기거래", "회사 손해 발생", "고의 인정"],
     {"타인 사무 처리자": True, "임무위배": True, "재산상 손해": True, "고의": True}, "and",
     "배임죄(355조 2항) 성립."),
    ("단순 위탁받은 물건을 일시 사용한 후 반환한 경우 횡령?",
     ["타인 재물 보관자", "불법영득의사", "횡령행위"],
     ["보관자", "반환의사 있음", "일시 사용"],
     {"타인 재물 보관자": True, "불법영득의사": False, "횡령행위": False}, "and",
     "불법영득의사 결여로 횡령 불성립."),
    ("이사가 회사 기회를 가로챈 경우의 배임 요건?",
     ["타인 사무 처리자", "임무위배", "재산상 이익 취득", "재산상 손해"],
     ["이사", "회사기회유용", "이득", "회사 손해"],
     {"타인 사무 처리자": True, "임무위배": True, "재산상 이익 취득": True, "재산상 손해": True}, "and",
     "업무상 배임 성립."),
    ("회사 명의 카드로 개인 사적 지출을 한 경우?",
     ["타인 재물 보관자", "업무상 임무", "횡령행위"],
     ["법인카드 관리", "업무용", "사적 사용"],
     {"타인 재물 보관자": True, "업무상 임무": True, "횡령행위": True}, "and",
     "업무상 횡령 성립."),

    # 공갈/협박
    ("A가 B에게 '돈 주지 않으면 비밀을 폭로하겠다'고 말해 500만원을 받았다. 공갈?",
     ["해악의 고지", "외포심", "처분행위", "재산상 이득"],
     ["해악 고지", "피해자 겁먹음", "송금", "500만원 이득"],
     {"해악의 고지": True, "외포심": True, "처분행위": True, "재산상 이득": True}, "and",
     "공갈죄(350조) 성립."),
    ("해악을 고지했으나 상대가 전혀 무서워하지 않고 처분도 없었던 경우?",
     ["해악의 고지", "외포심", "처분행위", "재산상 이득"],
     ["해악 고지", "무서워 안함", "처분 없음", "이득 없음"],
     {"해악의 고지": True, "외포심": False, "처분행위": False, "재산상 이득": False}, "and",
     "미수 검토(형법 352조)."),
    ("정당한 권리행사로 채무 변제를 요구한 경우 협박?",
     ["해악의 고지", "위법성"],
     ["변제요구", "정당한 권리"],
     {"해악의 고지": False, "위법성": False}, "and",
     "정당행위로 협박 불성립."),

    # 명예훼손/모욕
    ("SNS에 A가 B의 허위사실을 공개적으로 게시한 경우 명예훼손?",
     ["공연성", "사실적시", "허위사실", "명예훼손"],
     ["공개 게시", "사실 적시", "허위", "사회적 평가 저하"],
     {"공연성": True, "사실적시": True, "허위사실": True, "명예훼손": True}, "and",
     "허위사실적시 명예훼손(307조 2항) 성립."),
    ("일대일 비공개 대화에서 험담한 경우?",
     ["공연성", "사실적시", "명예훼손"],
     ["1:1 비공개", "사실적시", "전파가능성 낮음"],
     {"공연성": False, "사실적시": True, "명예훼손": True}, "and",
     "공연성 결여로 불성립."),
    ("공개된 자리에서 '바보'라는 경멸 표현만 사용한 경우?",
     ["공연성", "모욕적 표현"],
     ["공개", "경멸적 표현"],
     {"공연성": True, "모욕적 표현": True}, "and",
     "모욕죄(311조) 성립."),

    # 주거침입
    ("주거침입죄의 구성요건: A가 야간에 B의 주거에 창문으로 침입.",
     ["사람의 주거", "침입"],
     ["B의 주거", "야간 창문 침입"],
     {"사람의 주거": True, "침입": True}, "and",
     "주거침입죄(319조) 성립."),
    ("A가 B의 초대를 받고 들어간 경우 주거침입?",
     ["사람의 주거", "침입"],
     ["주거", "초대(승낙)"],
     {"사람의 주거": True, "침입": False}, "and",
     "승낙이 있어 침입에 해당하지 않음."),

    # 교통사고
    ("운전자가 횡단보도 신호 무시로 보행자 상해를 입힌 경우.",
     ["업무상 과실", "사고", "상해결과"],
     ["운전 중 신호위반", "사고 발생", "보행자 부상"],
     {"업무상 과실": True, "사고": True, "상해결과": True}, "and",
     "교통사고처리특례법상 업무상과실치상 성립."),
    ("음주운전으로 사망사고를 낸 경우의 가중요건?",
     ["음주운전", "사망사고", "인과관계"],
     ["혈중 0.15%", "피해자 사망", "음주와 사고 연관"],
     {"음주운전": True, "사망사고": True, "인과관계": True}, "and",
     "특정범죄가중법상 위험운전치사 성립."),

    # 강제추행/성범죄(민감 — 구성요건 서술만)
    ("폭행 또는 협박으로 추행한 경우 강제추행의 구성요건?",
     ["폭행 또는 협박", "추행"],
     ["협박 사용", "추행 행위"],
     {"폭행 또는 협박": True, "추행": True}, "and",
     "강제추행죄(298조) 성립."),

    # personal jurisdiction 스타일
    ("B is from state X, sued in state Y. Minimum contacts, purposeful availment, fair play — PJ?",
     ["minimum contacts", "purposeful availment", "fair play and substantial justice"],
     ["sold goods in Y", "targeted Y consumers", "reasonable to litigate"],
     {"minimum contacts": True, "purposeful availment": True, "fair play and substantial justice": True}, "and",
     "Specific personal jurisdiction is proper."),
    ("Defendant never sold in forum, no targeting, burden on defendant. PJ?",
     ["minimum contacts", "purposeful availment", "fair play and substantial justice"],
     ["no contacts", "no targeting", "burden heavy"],
     {"minimum contacts": False, "purposeful availment": False, "fair play and substantial justice": False}, "and",
     "No personal jurisdiction."),
    ("Defendant has contacts but litigation is unreasonably burdensome. PJ?",
     ["minimum contacts", "purposeful availment", "fair play and substantial justice"],
     ["some contacts", "availment", "unreasonable burden"],
     {"minimum contacts": True, "purposeful availment": True, "fair play and substantial justice": False}, "and",
     "PJ defeated by fair play prong."),
    ("General jurisdiction: defendant corporation is 'at home' in the forum state?",
     ["incorporated in forum", "principal place of business in forum"],
     ["corp incorporated in DE", "PPB in DE"],
     {"incorporated in forum": True, "principal place of business in forum": True}, "or",
     "General PJ satisfied (either prong)."),
    ("Stream-of-commerce: defendant knowingly sent product into forum?",
     ["minimum contacts", "purposeful availment"],
     ["stream of commerce", "targeted forum"],
     {"minimum contacts": True, "purposeful availment": True}, "and",
     "Specific PJ satisfied."),

    # hearsay 스타일
    ("Witness testifies about out-of-court statement to prove truth. Hearsay?",
     ["out-of-court statement", "offered for truth"],
     ["statement made outside court", "offered to prove content"],
     {"out-of-court statement": True, "offered for truth": True}, "and",
     "Hearsay."),
    ("Statement offered to show effect on listener, not for truth.",
     ["out-of-court statement", "offered for truth"],
     ["out-of-court statement", "offered for effect on listener"],
     {"out-of-court statement": True, "offered for truth": False}, "and",
     "Not hearsay (non-truth purpose)."),
    ("Statement by party-opponent offered against them.",
     ["out-of-court statement", "offered for truth", "party opponent admission"],
     ["statement", "against party", "party's own statement"],
     {"out-of-court statement": True, "offered for truth": True, "party opponent admission": True}, "and",
     "Admission by party-opponent — not hearsay (FRE 801(d)(2))."),
    ("Excited utterance exception: startling event, statement while under stress.",
     ["out-of-court statement", "offered for truth", "excited utterance"],
     ["startling event", "under stress", "relating to event"],
     {"out-of-court statement": True, "offered for truth": True, "excited utterance": True}, "and",
     "Hearsay, but admissible under excited utterance exception."),
    ("Witness' prior inconsistent statement offered to impeach, not for truth.",
     ["out-of-court statement", "offered for truth"],
     ["prior statement", "to impeach"],
     {"out-of-court statement": True, "offered for truth": False}, "and",
     "Not hearsay — impeachment purpose."),
    ("Business record kept in regular course of business.",
     ["out-of-court statement", "offered for truth", "business record"],
     ["record", "for truth", "regular business"],
     {"out-of-court statement": True, "offered for truth": True, "business record": True}, "and",
     "Admissible under business records exception (803(6))."),
    ("Present sense impression: describing event while perceiving it.",
     ["out-of-court statement", "offered for truth", "present sense impression"],
     ["contemporaneous description"]*1 + ["for truth", "while perceiving"],
     {"out-of-court statement": True, "offered for truth": True, "present sense impression": True}, "and",
     "Exception applies (803(1))."),
    ("Statement not made by human (machine printout).",
     ["out-of-court statement", "offered for truth"],
     ["machine output", "not a statement by declarant"],
     {"out-of-court statement": False, "offered for truth": True}, "and",
     "Not a hearsay statement — machines are not declarants."),
    ("Dying declaration about cause of death in homicide case.",
     ["out-of-court statement", "offered for truth", "dying declaration"],
     ["statement", "about cause", "imminent death"],
     {"out-of-court statement": True, "offered for truth": True, "dying declaration": True}, "and",
     "Admissible (804(b)(2))."),
    ("Statement against declarant's pecuniary interest, declarant unavailable.",
     ["out-of-court statement", "offered for truth", "statement against interest"],
     ["statement", "for truth", "declarant unavailable and statement against interest"],
     {"out-of-court statement": True, "offered for truth": True, "statement against interest": True}, "and",
     "Admissible (804(b)(3))."),

    # 민사/계약 요건
    ("계약 성립요건: 청약과 승낙의 합치.",
     ["청약", "승낙", "의사표시 합치"],
     ["매도청약", "매수승낙", "내용 일치"],
     {"청약": True, "승낙": True, "의사표시 합치": True}, "and",
     "계약 성립(민법 527조 이하)."),
    ("승낙이 지연되어 청약의 효력이 소멸한 경우?",
     ["청약", "승낙", "기간 내 승낙"],
     ["청약", "지연된 승낙", "기간 경과"],
     {"청약": True, "승낙": True, "기간 내 승낙": False}, "and",
     "새로운 청약으로 간주(계약 불성립)."),
    ("불법행위 성립요건: 고의/과실, 위법성, 손해, 인과관계.",
     ["고의 또는 과실", "위법성", "손해", "인과관계"],
     ["과실 있음", "위법 행위", "손해 발생", "인과 인정"],
     {"고의 또는 과실": True, "위법성": True, "손해": True, "인과관계": True}, "and",
     "불법행위책임(민법 750조) 성립."),
    ("위법성 조각사유(정당방위)가 인정된 경우?",
     ["고의 또는 과실", "위법성", "손해", "인과관계"],
     ["과실", "정당방위로 위법성 조각", "손해", "인과"],
     {"고의 또는 과실": True, "위법성": False, "손해": True, "인과관계": True}, "and",
     "위법성 조각으로 책임 불성립."),
    ("사용자책임: 피용자의 불법행위가 사무집행 관련성 있을 때.",
     ["사용관계", "사무집행 관련성", "피용자 불법행위"],
     ["사용관계", "업무 중", "불법행위"],
     {"사용관계": True, "사무집행 관련성": True, "피용자 불법행위": True}, "and",
     "사용자책임(756조) 성립."),

    # 점유/물권
    ("선의취득 요건: 동산, 점유취득, 평온공연, 선의무과실.",
     ["동산", "점유취득", "평온공연", "선의무과실"],
     ["동산매매", "점유이전", "평온공연", "선의무과실"],
     {"동산": True, "점유취득": True, "평온공연": True, "선의무과실": True}, "and",
     "선의취득(249조) 성립."),
    ("악의의 매수인이 도난품을 매수한 경우?",
     ["동산", "점유취득", "평온공연", "선의무과실"],
     ["도품", "점유", "공연", "악의"],
     {"동산": True, "점유취득": True, "평온공연": True, "선의무과실": False}, "and",
     "선의요건 결여로 선의취득 불성립."),

    # 노동
    ("부당해고 요건: 사용자-근로자, 해고, 정당한 사유 없음.",
     ["근로관계", "해고행위", "정당한 사유 없음"],
     ["근로자", "일방적 해고", "사유 부족"],
     {"근로관계": True, "해고행위": True, "정당한 사유 없음": True}, "and",
     "부당해고 성립."),
    ("정당한 징계해고 사유가 입증된 경우?",
     ["근로관계", "해고행위", "정당한 사유 없음"],
     ["근로자", "해고", "징계사유 충분"],
     {"근로관계": True, "해고행위": True, "정당한 사유 없음": False}, "and",
     "정당한 해고로 부당해고 불성립."),
]


# L02 specs: (user_q, rule_name, antecedents[], consequent, conditions{}, mode, explanation)
L02_SPECS = [
    ("형사책임 규칙: 고의 and 위법성 ⇒ 형사책임. 둘 다 있음.",
     "형사책임의 일반원칙", ["고의", "위법성"], "형사책임",
     {"고의": True, "위법성": True}, "and",
     "요건 충족으로 형사책임 성립."),
    ("위법성 조각사유 존재 시 형사책임?",
     "형사책임의 일반원칙", ["고의", "위법성"], "형사책임",
     {"고의": True, "위법성": False}, "and",
     "위법성 결여로 규칙 불발동."),
    ("계약 성립 규칙: 청약 and 승낙 ⇒ 계약성립.",
     "계약성립", ["청약", "승낙"], "계약성립",
     {"청약": True, "승낙": True}, "and", "계약 성립."),
    ("승낙 없으면 계약 성립?",
     "계약성립", ["청약", "승낙"], "계약성립",
     {"청약": True, "승낙": False}, "and", "계약 불성립."),
    ("소멸시효: 채권발생 and 기간도과 and 원용 ⇒ 소멸.",
     "채권의 소멸시효", ["채권발생", "기간도과", "원용"], "채권소멸",
     {"채권발생": True, "기간도과": True, "원용": True}, "and", "시효 완성으로 소멸."),
    ("기간 미도과 시 소멸시효?",
     "채권의 소멸시효", ["채권발생", "기간도과", "원용"], "채권소멸",
     {"채권발생": True, "기간도과": False, "원용": True}, "and", "미완성."),
    ("정당방위: 부당한 침해 and 자기나 타인 법익 방위 and 상당성 ⇒ 위법성조각.",
     "정당방위", ["부당한침해", "방위행위", "상당성"], "위법성조각",
     {"부당한침해": True, "방위행위": True, "상당성": True}, "and", "정당방위 성립."),
    ("상당성 초과하는 방어행위의 경우?",
     "정당방위", ["부당한침해", "방위행위", "상당성"], "위법성조각",
     {"부당한침해": True, "방위행위": True, "상당성": False}, "and", "과잉방위(면책감경)."),
    ("업무상과실치사상죄: 업무상 과실 and 사상결과 ⇒ 처벌.",
     "업무상과실치사상", ["업무상 과실", "사상결과"], "처벌",
     {"업무상 과실": True, "사상결과": True}, "and", "처벌."),
    ("미성년자 계약의 취소 가능성: 미성년자 and 법정대리인 동의 없음 ⇒ 취소가능.",
     "미성년자 계약 취소", ["미성년자", "법정대리인 동의 없음"], "취소가능",
     {"미성년자": True, "법정대리인 동의 없음": True}, "and", "취소 가능."),
    ("미성년자라도 법정대리인 동의가 있다면?",
     "미성년자 계약 취소", ["미성년자", "법정대리인 동의 없음"], "취소가능",
     {"미성년자": True, "법정대리인 동의 없음": False}, "and", "취소 불가."),
    ("의사의 설명의무 위반: 의료행위 and 중대한 위험 설명누락 ⇒ 손해배상.",
     "설명의무 위반", ["의료행위", "중대위험 설명누락"], "손해배상책임",
     {"의료행위": True, "중대위험 설명누락": True}, "and", "배상책임."),
    ("설명의무 이행된 경우?",
     "설명의무 위반", ["의료행위", "중대위험 설명누락"], "손해배상책임",
     {"의료행위": True, "중대위험 설명누락": False}, "and", "책임 없음."),
    ("제조물책임: 제조물의 결함 and 손해 and 인과관계 ⇒ 제조사 책임.",
     "제조물책임", ["결함", "손해", "인과관계"], "제조사책임",
     {"결함": True, "손해": True, "인과관계": True}, "and", "책임 성립."),
    ("결함이 없는 경우?",
     "제조물책임", ["결함", "손해", "인과관계"], "제조사책임",
     {"결함": False, "손해": True, "인과관계": True}, "and", "불성립."),
    ("상표권 침해: 등록상표 and 동일유사 사용 and 혼동가능성 ⇒ 침해.",
     "상표권 침해", ["등록상표", "동일유사 사용", "혼동가능성"], "침해",
     {"등록상표": True, "동일유사 사용": True, "혼동가능성": True}, "and", "침해."),
    ("혼동가능성이 없는 경우?",
     "상표권 침해", ["등록상표", "동일유사 사용", "혼동가능성"], "침해",
     {"등록상표": True, "동일유사 사용": True, "혼동가능성": False}, "and", "침해 부정."),
    ("공동정범: 공동의사 and 공동실행 ⇒ 공동정범.",
     "공동정범", ["공동의사", "공동실행"], "공동정범",
     {"공동의사": True, "공동실행": True}, "and", "성립."),
    ("공동의사 없이 우연적 가세한 경우?",
     "공동정범", ["공동의사", "공동실행"], "공동정범",
     {"공동의사": False, "공동실행": True}, "and", "공동정범 부정."),
    ("긴급피난: 위난 and 피난행위 and 보충성 and 상당성 ⇒ 위법성조각.",
     "긴급피난", ["위난", "피난행위", "보충성", "상당성"], "위법성조각",
     {"위난": True, "피난행위": True, "보충성": True, "상당성": True}, "and", "긴급피난."),
    ("하자담보책임: 하자 and 선의무과실 매수인 ⇒ 해제/대금감액.",
     "매수인 하자담보책임", ["하자", "선의무과실"], "해제대금감액",
     {"하자": True, "선의무과실": True}, "and", "인정."),
    ("악의의 매수인인 경우?",
     "매수인 하자담보책임", ["하자", "선의무과실"], "해제대금감액",
     {"하자": True, "선의무과실": False}, "and", "불인정."),
    ("동시이행항변권: 쌍무계약 and 상대방 불이행 ⇒ 이행거절권.",
     "동시이행항변권", ["쌍무계약", "상대방 불이행"], "이행거절권",
     {"쌍무계약": True, "상대방 불이행": True}, "and", "항변권 발동."),
    ("편무계약인 경우?",
     "동시이행항변권", ["쌍무계약", "상대방 불이행"], "이행거절권",
     {"쌍무계약": False, "상대방 불이행": True}, "and", "부인."),
    ("행정처분 취소 사유: 위법성 OR 재량남용 ⇒ 취소.",
     "행정처분 취소", ["위법성", "재량남용"], "취소",
     {"위법성": True, "재량남용": False}, "or", "취소 사유 인정."),
    ("둘 다 없는 경우?",
     "행정처분 취소", ["위법성", "재량남용"], "취소",
     {"위법성": False, "재량남용": False}, "or", "취소 사유 없음."),
    ("국가배상: 공무원 직무상 행위 and 위법 and 고의과실 and 손해 ⇒ 배상.",
     "국가배상", ["공무원 직무상 행위", "위법", "고의과실", "손해"], "국가배상책임",
     {"공무원 직무상 행위": True, "위법": True, "고의과실": True, "손해": True}, "and", "성립."),
    ("고의과실이 없는 경우?",
     "국가배상", ["공무원 직무상 행위", "위법", "고의과실", "손해"], "국가배상책임",
     {"공무원 직무상 행위": True, "위법": True, "고의과실": False, "손해": True}, "and", "불성립."),
    ("명예훼손 성립: 공연성 and 사실적시 ⇒ 명예훼손.",
     "명예훼손", ["공연성", "사실적시"], "명예훼손",
     {"공연성": True, "사실적시": True}, "and", "성립."),
    ("허위사실 가중: 공연성 and 사실적시 and 허위 ⇒ 가중.",
     "허위사실 명예훼손 가중", ["공연성", "사실적시", "허위"], "가중처벌",
     {"공연성": True, "사실적시": True, "허위": True}, "and", "가중."),
    ("공익성 인정 시 위법성 조각.",
     "공익 명예훼손 조각", ["사실적시", "공익성", "진실성"], "위법성조각",
     {"사실적시": True, "공익성": True, "진실성": True}, "and", "조각."),
    ("이혼 청구사유 유책: 부정행위 OR 악의유기 OR 기타중대사유 ⇒ 이혼.",
     "재판상 이혼사유", ["부정행위", "악의유기", "기타중대사유"], "이혼허가",
     {"부정행위": True, "악의유기": False, "기타중대사유": False}, "or", "이혼사유 인정."),
    ("사유가 모두 없는 경우?",
     "재판상 이혼사유", ["부정행위", "악의유기", "기타중대사유"], "이혼허가",
     {"부정행위": False, "악의유기": False, "기타중대사유": False}, "or", "기각."),
    ("법인격 부인: 법인형식 남용 and 실질적 동일성 ⇒ 법인격 부인.",
     "법인격 부인", ["법인형식 남용", "실질적 동일성"], "법인격부인",
     {"법인형식 남용": True, "실질적 동일성": True}, "and", "부인."),
    ("기각 사례.",
     "법인격 부인", ["법인형식 남용", "실질적 동일성"], "법인격부인",
     {"법인형식 남용": False, "실질적 동일성": True}, "and", "기각."),
    ("상속 결격: 고의 살해 OR 유언방해 ⇒ 상속결격.",
     "상속결격", ["고의살해", "유언방해"], "상속결격",
     {"고의살해": False, "유언방해": True}, "or", "결격."),
    ("둘 다 없음.",
     "상속결격", ["고의살해", "유언방해"], "상속결격",
     {"고의살해": False, "유언방해": False}, "or", "상속자격 유지."),
    ("채권자취소권: 사해행위 and 악의 ⇒ 취소.",
     "채권자취소권", ["사해행위", "수익자의 악의"], "취소",
     {"사해행위": True, "수익자의 악의": True}, "and", "취소."),
    ("선의 수익자.",
     "채권자취소권", ["사해행위", "수익자의 악의"], "취소",
     {"사해행위": True, "수익자의 악의": False}, "and", "불가."),
    ("임대차 묵시적 갱신: 기간만료 and 이의 없음 ⇒ 갱신.",
     "묵시적 갱신", ["기간만료", "이의없음"], "갱신",
     {"기간만료": True, "이의없음": True}, "and", "갱신."),
    ("이의 있음.",
     "묵시적 갱신", ["기간만료", "이의없음"], "갱신",
     {"기간만료": True, "이의없음": False}, "and", "종료."),
    ("과실상계: 피해자 과실 있음 ⇒ 배상액 감액.",
     "과실상계", ["피해자 과실"], "배상액 감액",
     {"피해자 과실": True}, "and", "감액."),
    ("피해자 과실 없음.",
     "과실상계", ["피해자 과실"], "배상액 감액",
     {"피해자 과실": False}, "and", "감액 없음."),
    ("정당행위: 법령행위 OR 업무행위 OR 사회상규 ⇒ 위법성조각.",
     "정당행위", ["법령행위", "업무행위", "사회상규"], "위법성조각",
     {"법령행위": False, "업무행위": True, "사회상규": False}, "or", "조각."),
    ("셋 다 부정.",
     "정당행위", ["법령행위", "업무행위", "사회상규"], "위법성조각",
     {"법령행위": False, "업무행위": False, "사회상규": False}, "or", "조각 없음."),
    ("공소시효 완성: 범죄 and 기간도과 ⇒ 면소.",
     "공소시효", ["범죄성립", "기간도과"], "면소",
     {"범죄성립": True, "기간도과": True}, "and", "면소."),
    ("기간 도과 전.",
     "공소시효", ["범죄성립", "기간도과"], "면소",
     {"범죄성립": True, "기간도과": False}, "and", "공소 가능."),
    ("손해배상 청구권: 불법행위 and 손해 and 인과관계 ⇒ 청구권.",
     "불법행위 손해배상", ["불법행위", "손해", "인과관계"], "청구권",
     {"불법행위": True, "손해": True, "인과관계": True}, "and", "청구 가능."),
    ("인과관계 부정.",
     "불법행위 손해배상", ["불법행위", "손해", "인과관계"], "청구권",
     {"불법행위": True, "손해": True, "인과관계": False}, "and", "기각."),
    ("저작권 침해: 저작물 and 복제 and 무단 ⇒ 침해.",
     "저작권 침해", ["저작물성", "복제행위", "무단"], "침해",
     {"저작물성": True, "복제행위": True, "무단": True}, "and", "침해."),
    ("허락 받음.",
     "저작권 침해", ["저작물성", "복제행위", "무단"], "침해",
     {"저작물성": True, "복제행위": True, "무단": False}, "and", "불침해."),
]


# L03 specs: (user_q, norm_name, elements[], facts[], subsumption{}, explanation)
L03_SPECS = [
    ("편의점 음료 절취 사건을 형법 329조에 포섭하라.",
     "형법 제329조(절도)", ["타인의 재물", "절취", "불법영득의사"],
     ["편의점 음료", "주머니 은닉 후 퇴장", "불법영득 의도"],
     {"타인의 재물": True, "절취": True, "불법영득의사": True},
     "절도 구성요건 포섭."),
    ("자신 소유물을 가져간 경우를 329조에 포섭.",
     "형법 제329조(절도)", ["타인의 재물", "절취", "불법영득의사"],
     ["자기 물건", "가져감", "의사 없음"],
     {"타인의 재물": False, "절취": False, "불법영득의사": False},
     "절도 불포섭."),
    ("의사의 수술행위를 상해죄(257조)에 포섭할 수 있는가?",
     "형법 제257조(상해)", ["신체의 완전성 침해", "고의"],
     ["수술로 절개", "업무상 승낙"],
     {"신체의 완전성 침해": True, "고의": False},
     "고의·위법성 요건 미충족, 업무상 정당행위로 포섭 불가."),
    ("의사의 설명 없이 수술한 경우 상해?",
     "형법 제257조(상해)", ["신체의 완전성 침해", "고의"],
     ["무단수술", "인식 있음"],
     {"신체의 완전성 침해": True, "고의": True},
     "상해 구성요건 포섭(승낙 결여)."),
    ("단체채팅방 험담을 모욕죄(311조)에 포섭.",
     "형법 제311조(모욕)", ["공연성", "모욕적 표현"],
     ["단체채팅방", "경멸 표현"],
     {"공연성": True, "모욕적 표현": True},
     "모욕 포섭."),
    ("1:1 DM 모욕?",
     "형법 제311조(모욕)", ["공연성", "모욕적 표현"],
     ["사적 DM", "모욕 표현"],
     {"공연성": False, "모욕적 표현": True},
     "공연성 결여 불포섭."),
    ("회사돈 개인사용 사건을 업무상 횡령(356)에 포섭.",
     "형법 제356조(업무상 횡령)", ["타인재물 보관", "업무상 임무", "횡령"],
     ["회사자금", "경리업무", "개인유용"],
     {"타인재물 보관": True, "업무상 임무": True, "횡령": True}, "포섭."),
    ("보관이 아닌 단순 점유자 사건?",
     "형법 제356조(업무상 횡령)", ["타인재물 보관", "업무상 임무", "횡령"],
     ["단순소지", "업무 외", "유용"],
     {"타인재물 보관": False, "업무상 임무": False, "횡령": True}, "불포섭(다른 죄명 검토)."),
    ("교통사고를 업무상과실치상에 포섭.",
     "형법 제268조(업무상과실치상)", ["업무상 과실", "상해결과", "인과"],
     ["운전 중 신호위반", "상해", "인과"],
     {"업무상 과실": True, "상해결과": True, "인과": True}, "포섭."),
    ("보행자 과실만 있는 경우?",
     "형법 제268조(업무상과실치상)", ["업무상 과실", "상해결과", "인과"],
     ["보행자 과실", "상해", "인과 단절"],
     {"업무상 과실": False, "상해결과": True, "인과": False}, "불포섭."),
    ("허위 세금계산서 발급을 조세범처벌법에 포섭.",
     "조세범처벌법 제10조", ["계산서 발급의무", "허위 기재", "조세포탈 목적"],
     ["사업자", "허위 금액", "포탈 의도"],
     {"계산서 발급의무": True, "허위 기재": True, "조세포탈 목적": True}, "포섭."),
    ("사실 그대로 발급.",
     "조세범처벌법 제10조", ["계산서 발급의무", "허위 기재", "조세포탈 목적"],
     ["정상 발급", "사실기재", "목적 없음"],
     {"계산서 발급의무": True, "허위 기재": False, "조세포탈 목적": False}, "불포섭."),
    ("아파트 층간소음 사건을 경범죄처벌법에 포섭.",
     "경범죄처벌법 제3조(인근소란)", ["소란행위", "주거지역"],
     ["심야 피아노", "아파트"],
     {"소란행위": True, "주거지역": True}, "포섭."),
    ("공업지역 낮 소음?",
     "경범죄처벌법 제3조(인근소란)", ["소란행위", "주거지역"],
     ["주간 공사소음", "공업지역"],
     {"소란행위": True, "주거지역": False}, "불포섭."),
    ("공무원 뇌물수수를 형법 129조에 포섭.",
     "형법 제129조(수뢰)", ["공무원", "직무관련", "수수"],
     ["공무원", "직무 관련", "금품수수"],
     {"공무원": True, "직무관련": True, "수수": True}, "포섭."),
    ("직무 무관한 증여?",
     "형법 제129조(수뢰)", ["공무원", "직무관련", "수수"],
     ["공무원", "개인관계 선물", "수수"],
     {"공무원": True, "직무관련": False, "수수": True}, "불포섭."),
    ("배우자 외도로 인한 이혼청구를 840조 1호에 포섭.",
     "민법 제840조 1호(부정행위)", ["배우자 부정행위"],
     ["혼외성관계"],
     {"배우자 부정행위": True}, "포섭."),
    ("단순 대화?",
     "민법 제840조 1호(부정행위)", ["배우자 부정행위"],
     ["친구와 대화"],
     {"배우자 부정행위": False}, "불포섭."),
    ("2년 이상 별거를 840조 6호에 포섭.",
     "민법 제840조 6호(기타 중대사유)", ["혼인관계 파탄", "중대사유"],
     ["5년 별거", "관계 회복 불능"],
     {"혼인관계 파탄": True, "중대사유": True}, "포섭."),
    ("일시적 별거?",
     "민법 제840조 6호(기타 중대사유)", ["혼인관계 파탄", "중대사유"],
     ["1개월 별거", "화해중"],
     {"혼인관계 파탄": False, "중대사유": False}, "불포섭."),
    ("직장 성희롱을 남녀고용평등법에 포섭.",
     "남녀고용평등법 제12조", ["직장 내", "성적 언동", "불이익"],
     ["회사 내", "성적 농담 반복", "인사 불이익"],
     {"직장 내": True, "성적 언동": True, "불이익": True}, "포섭."),
    ("회식 외 우연한 만남?",
     "남녀고용평등법 제12조", ["직장 내", "성적 언동", "불이익"],
     ["사적 만남", "언동", "불이익 없음"],
     {"직장 내": False, "성적 언동": True, "불이익": False}, "불포섭."),
    ("음주운전 0.15%를 특가법에 포섭.",
     "특정범죄가중법(위험운전치사상)", ["위험운전", "사고", "사상"],
     ["0.18% 음주", "충돌", "사망"],
     {"위험운전": True, "사고": True, "사상": True}, "포섭."),
    ("혈중 0.02% 추돌?",
     "특정범죄가중법(위험운전치사상)", ["위험운전", "사고", "사상"],
     ["저농도", "경미 추돌", "부상 없음"],
     {"위험운전": False, "사고": True, "사상": False}, "불포섭."),
    ("폭행 후 증거인멸을 증거인멸죄에 포섭.",
     "형법 제155조(증거인멸)", ["타인 형사사건 증거", "인멸"],
     ["피의자 친구의 증거", "파기"],
     {"타인 형사사건 증거": True, "인멸": True}, "포섭."),
    ("자기 사건 증거?",
     "형법 제155조(증거인멸)", ["타인 형사사건 증거", "인멸"],
     ["자기 사건 증거", "파기"],
     {"타인 형사사건 증거": False, "인멸": True}, "불포섭(자기증거 은닉은 처벌대상 아님)."),
    ("협박 편지를 협박죄(283)에 포섭.",
     "형법 제283조(협박)", ["해악의 고지", "상대방 인식"],
     ["살해 협박문자", "피해자 수신·인식"],
     {"해악의 고지": True, "상대방 인식": True}, "포섭."),
    ("전달되지 않은 미발송 편지?",
     "형법 제283조(협박)", ["해악의 고지", "상대방 인식"],
     ["작성만 함", "미전달"],
     {"해악의 고지": False, "상대방 인식": False}, "불포섭."),
    ("개인정보보호법 위반(유출)에 포섭.",
     "개인정보보호법 제71조", ["개인정보처리자", "정보 유출", "고의"],
     ["쇼핑몰 관리자", "고객정보 판매", "고의"],
     {"개인정보처리자": True, "정보 유출": True, "고의": True}, "포섭."),
    ("해킹 피해자가 유출된 경우?",
     "개인정보보호법 제71조", ["개인정보처리자", "정보 유출", "고의"],
     ["처리자가 피해자", "유출 결과", "고의 없음"],
     {"개인정보처리자": True, "정보 유출": True, "고의": False}, "불포섭(관리감독 책임은 별개)."),
    ("무면허 의료행위를 의료법 27조에 포섭.",
     "의료법 제27조", ["무자격자", "의료행위"],
     ["자격 없음", "수술 시행"],
     {"무자격자": True, "의료행위": True}, "포섭."),
    ("의사가 한 수술?",
     "의료법 제27조", ["무자격자", "의료행위"],
     ["면허 의사", "수술"],
     {"무자격자": False, "의료행위": True}, "불포섭."),
    ("자본시장법상 미공개정보 이용을 포섭.",
     "자본시장법 제174조", ["내부자", "미공개 중요정보", "이용"],
     ["임원", "미공개 M&A 정보", "매매에 이용"],
     {"내부자": True, "미공개 중요정보": True, "이용": True}, "포섭."),
    ("공개 후 거래?",
     "자본시장법 제174조", ["내부자", "미공개 중요정보", "이용"],
     ["내부자", "공시 후", "거래"],
     {"내부자": True, "미공개 중요정보": False, "이용": True}, "불포섭."),
    ("공직선거법상 허위사실 공표에 포섭.",
     "공직선거법 제250조", ["후보자 관련", "허위사실 공표", "당선 목적"],
     ["상대후보 허위 경력", "SNS 공표", "선거 영향 의도"],
     {"후보자 관련": True, "허위사실 공표": True, "당선 목적": True}, "포섭."),
    ("진실사실 공표?",
     "공직선거법 제250조", ["후보자 관련", "허위사실 공표", "당선 목적"],
     ["후보자 관련", "사실 공표", "의도 있음"],
     {"후보자 관련": True, "허위사실 공표": False, "당선 목적": True}, "불포섭."),
    ("마약류관리법 위반(투약)에 포섭.",
     "마약류관리법 제61조", ["마약류", "투약·소지", "고의"],
     ["메스암페타민", "투약", "고의"],
     {"마약류": True, "투약·소지": True, "고의": True}, "포섭."),
    ("처방된 의약품 복용?",
     "마약류관리법 제61조", ["마약류", "투약·소지", "고의"],
     ["처방약", "복용", "합법"],
     {"마약류": False, "투약·소지": True, "고의": False}, "불포섭."),
    ("군형법상 명령불복종에 포섭.",
     "군형법 제44조", ["군인", "정당한 명령", "불복종"],
     ["현역군인", "합법명령", "고의적 거부"],
     {"군인": True, "정당한 명령": True, "불복종": True}, "포섭."),
    ("위법한 명령?",
     "군형법 제44조", ["군인", "정당한 명령", "불복종"],
     ["군인", "위법명령", "거부"],
     {"군인": True, "정당한 명령": False, "불복종": True}, "불포섭."),
    ("부정수표단속법에 포섭.",
     "부정수표단속법 제2조", ["수표발행", "예금부족", "고의"],
     ["수표발행", "부도", "고의 인정"],
     {"수표발행": True, "예금부족": True, "고의": True}, "포섭."),
    ("착오로 발행?",
     "부정수표단속법 제2조", ["수표발행", "예금부족", "고의"],
     ["발행", "부도", "과실"],
     {"수표발행": True, "예금부족": True, "고의": False}, "불포섭."),
    ("textualism: statute's plain meaning governs — 'vehicle' includes motorbike?",
     "Plain meaning rule", ["ordinary meaning", "statutory text"],
     ["motorbike is vehicle ordinarily", "text says 'no vehicles'"],
     {"ordinary meaning": True, "statutory text": True}, "Subsumed under plain meaning."),
    ("Does 'vehicle' include a toy car?",
     "Plain meaning rule", ["ordinary meaning", "statutory text"],
     ["toy is not ordinary vehicle", "text 'vehicles'"],
     {"ordinary meaning": False, "statutory text": True}, "Not subsumed."),
    ("교통사고처리특례법상 중과실 12대 중과실 포섭.",
     "교통사고처리특례법 제3조", ["12대 중과실", "사상"],
     ["신호위반", "상해"],
     {"12대 중과실": True, "사상": True}, "포섭(반의사불벌 예외)."),
    ("단순 과실.",
     "교통사고처리특례법 제3조", ["12대 중과실", "사상"],
     ["전방주시 태만", "경미 상해"],
     {"12대 중과실": False, "사상": True}, "불포섭(반의사불벌)."),
    ("아동복지법상 아동학대에 포섭.",
     "아동복지법 제17조", ["아동", "학대행위"],
     ["7세", "체벌"],
     {"아동": True, "학대행위": True}, "포섭."),
    ("훈육으로 적정한 경우?",
     "아동복지법 제17조", ["아동", "학대행위"],
     ["아동", "적정 훈육"],
     {"아동": True, "학대행위": False}, "불포섭."),
    ("스토킹처벌법 포섭.",
     "스토킹처벌법 제2조", ["반복성", "상대방 불안 야기"],
     ["다수 접근", "불안감 유발"],
     {"반복성": True, "상대방 불안 야기": True}, "포섭."),
    ("1회 접근?",
     "스토킹처벌법 제2조", ["반복성", "상대방 불안 야기"],
     ["1회", "불안"],
     {"반복성": False, "상대방 불안 야기": True}, "불포섭."),
]


# L04 specs: (user_q, variables[], premises[], conclusion, valid_bool, explanation)
L04_SPECS = [
    ("Modus Ponens: P→Q, P ⊢ Q", ["P","Q"], ["P => Q", "P"], "Q",
     "Valid — modus ponens."),
    ("Modus Tollens: P→Q, ¬Q ⊢ ¬P", ["P","Q"], ["P => Q", "not Q"], "not P",
     "Valid — modus tollens."),
    ("Affirming the consequent: P→Q, Q ⊢ P", ["P","Q"], ["P => Q", "Q"], "P",
     "Invalid — fallacy."),
    ("Denying the antecedent: P→Q, ¬P ⊢ ¬Q", ["P","Q"], ["P => Q", "not P"], "not Q",
     "Invalid."),
    ("Disjunctive syllogism: P∨Q, ¬P ⊢ Q", ["P","Q"], ["P or Q", "not P"], "Q",
     "Valid."),
    ("Hypothetical syllogism: P→Q, Q→R ⊢ P→R", ["P","Q","R"], ["P => Q", "Q => R"], "P => R",
     "Valid."),
    ("Constructive dilemma", ["P","Q","R","S"], ["(P => Q) and (R => S)", "P or R"], "Q or S",
     "Valid."),
    ("And-intro: P, Q ⊢ P∧Q", ["P","Q"], ["P","Q"], "P and Q", "Valid."),
    ("And-elim: P∧Q ⊢ P", ["P","Q"], ["P and Q"], "P", "Valid."),
    ("Or-intro: P ⊢ P∨Q", ["P","Q"], ["P"], "P or Q", "Valid."),
    ("Negation elim: ¬¬P ⊢ P", ["P"], ["not not P"], "P", "Valid."),
    ("Contradiction fallacy: P, ¬P ⊢ anything (ex falso)", ["P","Q"], ["P", "not P"], "Q",
     "Valid (ex falso quodlibet)."),
    ("If guilty and negligent then liable; guilty, negligent ⇒ liable.",
     ["guilty","negligent","liable"], ["(guilty and negligent) => liable", "guilty", "negligent"],
     "liable", "Valid."),
    ("If guilty then liable; not guilty ⇒ not liable (invalid).",
     ["guilty","liable"], ["guilty => liable", "not guilty"], "not liable", "Invalid."),
    ("Contract: offer∧acceptance ⇒ formation; offer∧acceptance ⇒ formation.",
     ["offer","acceptance","formation"],
     ["(offer and acceptance) => formation", "offer", "acceptance"],
     "formation", "Valid."),
    ("No acceptance: conclude formation (invalid).",
     ["offer","acceptance","formation"],
     ["(offer and acceptance) => formation", "offer", "not acceptance"],
     "formation", "Invalid."),
    ("Duty∧breach∧causation∧harm ⇒ negligence liable.",
     ["duty","breach","cause","harm","liable"],
     ["(duty and breach and cause and harm) => liable", "duty", "breach", "cause", "harm"],
     "liable", "Valid."),
    ("Missing harm:",
     ["duty","breach","cause","harm","liable"],
     ["(duty and breach and cause and harm) => liable", "duty", "breach", "cause", "not harm"],
     "liable", "Invalid."),
    ("PJ: (MC and PA and FP) ⇒ PJ; all true ⇒ PJ.",
     ["MC","PA","FP","PJ"],
     ["(MC and PA and FP) => PJ", "MC", "PA", "FP"],
     "PJ", "Valid."),
    ("Missing FP:",
     ["MC","PA","FP","PJ"],
     ["(MC and PA and FP) => PJ", "MC", "PA", "not FP"],
     "PJ", "Invalid."),
    ("Hearsay: (OOC and forTruth) ⇒ hearsay; both ⇒ hearsay.",
     ["OOC","forTruth","hearsay"],
     ["(OOC and forTruth) => hearsay", "OOC", "forTruth"],
     "hearsay", "Valid."),
    ("Not for truth:",
     ["OOC","forTruth","hearsay"],
     ["(OOC and forTruth) => hearsay", "OOC", "not forTruth"],
     "not hearsay", "Invalid (denial of antecedent)."),
    ("De Morgan: ¬(P∧Q) ⊢ ¬P∨¬Q",
     ["P","Q"], ["not (P and Q)"], "(not P) or (not Q)", "Valid."),
    ("De Morgan reverse:",
     ["P","Q"], ["(not P) or (not Q)"], "not (P and Q)", "Valid."),
    ("Biconditional: P↔Q, P ⊢ Q",
     ["P","Q"], ["P <=> Q", "P"], "Q", "Valid."),
    ("P↔Q, ¬P ⊢ ¬Q",
     ["P","Q"], ["P <=> Q", "not P"], "not Q", "Valid."),
    ("Self-contradiction premise → any conclusion valid (trivial).",
     ["P","Q"], ["P and not P"], "Q", "Valid (vacuous)."),
    ("Tautology conclusion: ⊢ P or not P.",
     ["P"], [], "P or (not P)", "Valid (tautology)."),
    ("Non-tautology without premises:",
     ["P"], [], "P", "Invalid (no premise forces P)."),
    ("Nested implication: (P→Q)→R, P→Q ⊢ R",
     ["P","Q","R"], ["(P => Q) => R", "P => Q"], "R", "Valid."),
    ("Resolution: (P or Q) and (¬P or R) ⊢ Q or R",
     ["P","Q","R"], ["P or Q", "(not P) or R"], "Q or R", "Valid."),
    ("Guilty→prison; innocent→freedom; guilty ⊢ prison.",
     ["guilty","prison","innocent","freedom"],
     ["guilty => prison", "innocent => freedom", "guilty"],
     "prison", "Valid."),
    ("Guilty→prison, ¬prison ⊢ ¬guilty (modus tollens).",
     ["guilty","prison"], ["guilty => prison", "not prison"], "not guilty", "Valid."),
    ("범죄성립 and 공소시효 미완성 ⇒ 기소 가능",
     ["범죄성립","시효미완성","기소가능"],
     ["(범죄성립 and 시효미완성) => 기소가능", "범죄성립", "시효미완성"],
     "기소가능", "Valid."),
    ("시효 완성 시 기소 가능?",
     ["범죄성립","시효미완성","기소가능"],
     ["(범죄성립 and 시효미완성) => 기소가능", "범죄성립", "not 시효미완성"],
     "기소가능", "Invalid."),
    ("정당방위 ⇒ 위법성조각, 정당방위 ⊢ 위법성조각",
     ["정당방위","위법성조각"],
     ["정당방위 => 위법성조각", "정당방위"], "위법성조각", "Valid."),
    ("정당방위 ⇒ 조각, ¬조각 ⊢ ¬정당방위.",
     ["정당방위","위법성조각"],
     ["정당방위 => 위법성조각", "not 위법성조각"], "not 정당방위", "Valid."),
    ("¬(P or Q) ⊢ ¬P and ¬Q (De Morgan)",
     ["P","Q"], ["not (P or Q)"], "(not P) and (not Q)", "Valid."),
    ("P and Q ⊢ Q and P (comm)",
     ["P","Q"], ["P and Q"], "Q and P", "Valid."),
    ("(P or Q) and R ⊢ (P and R) or (Q and R) (distrib)",
     ["P","Q","R"], ["(P or Q) and R"], "(P and R) or (Q and R)", "Valid."),
    ("P→(Q→R), P, Q ⊢ R",
     ["P","Q","R"], ["P => (Q => R)", "P", "Q"], "R", "Valid."),
    ("Only-if: P only if Q, ¬Q ⊢ ¬P (same as modus tollens)",
     ["P","Q"], ["P => Q", "not Q"], "not P", "Valid."),
    ("If-then contradiction: P→Q, P→¬Q ⊢ ¬P",
     ["P","Q"], ["P => Q", "P => (not Q)"], "not P", "Valid."),
    ("Existential fallacy sketch (propositional proxy):",
     ["A","B"], ["A => B"], "B", "Invalid."),
    ("Double implication: P→Q, Q→P ⊢ P↔Q",
     ["P","Q"], ["P => Q", "Q => P"], "P <=> Q", "Valid."),
    ("Absorption: P→Q ⊢ P → (P and Q)",
     ["P","Q"], ["P => Q"], "P => (P and Q)", "Valid."),
    ("Self-implication: ⊢ P → P",
     ["P"], [], "P => P", "Valid."),
    ("Proof by cases: P∨Q, P→R, Q→R ⊢ R",
     ["P","Q","R"], ["P or Q", "P => R", "Q => R"], "R", "Valid."),
    ("If acceptance but no offer, still formation? invalid.",
     ["offer","acc","form"],
     ["(offer and acc) => form", "acc", "not offer"],
     "form", "Invalid."),
]


# L05 specs: (user_q, expr, vars, method, expected_value_or_solutions, round_to, target, explanation)
L05_SPECS = [
    ("원금 1천만원, 이율 5%, 기간 3년의 단리 이자는?",
     "principal*rate*years", {"principal":10000000,"rate":0.05,"years":3}, "eval", 1500000.0, 2, None,
     "단리 이자 = 원금 × 이율 × 기간."),
    ("원금 2천만원, 연 6%, 2년 단리 이자?",
     "principal*rate*years", {"principal":20000000,"rate":0.06,"years":2}, "eval", 2400000.0, 2, None, "."),
    ("원금 500만원, 연 4%, 5년 단리?",
     "principal*rate*years", {"principal":5000000,"rate":0.04,"years":5}, "eval", 1000000.0, 2, None, "."),
    ("복리 계산: P*(1+r)^n, 1000만원 연 5% 3년.",
     "principal*(1+rate)**years", {"principal":10000000,"rate":0.05,"years":3}, "eval",
     round(10000000*(1.05**3),2), 2, None, "복리."),
    ("복리 2000만원 연 3% 5년.",
     "principal*(1+rate)**years", {"principal":20000000,"rate":0.03,"years":5}, "eval",
     round(20000000*(1.03**5),2), 2, None, "."),
    ("월 복리 이자 총액: P*(1+r/12)^(12n).",
     "principal*(1+rate/12)**(12*years)", {"principal":10000000,"rate":0.06,"years":2}, "eval",
     round(10000000*(1+0.06/12)**(24),2), 2, None, "월복리."),
    ("지연손해금: 원금*연5%*지연일수/365, 500만원 30일.",
     "principal*rate*days/365", {"principal":5000000,"rate":0.05,"days":30}, "eval",
     round(5000000*0.05*30/365,2), 2, None, "."),
    ("지연손해금 100일, 1천만원, 연 12%.",
     "principal*rate*days/365", {"principal":10000000,"rate":0.12,"days":100}, "eval",
     round(10000000*0.12*100/365,2), 2, None, "."),
    ("손해배상 총액 = 치료비 + 일실수입 + 위자료.",
     "med + income + solatium", {"med":3000000,"income":5000000,"solatium":2000000}, "eval",
     10000000.0, 2, None, "."),
    ("치료비 500, 일실 1000, 위자료 300만원.",
     "med + income + solatium", {"med":5000000,"income":10000000,"solatium":3000000}, "eval",
     18000000.0, 2, None, "."),
    ("과실상계: 전체손해 * (1 - 과실비율). 손해 1천만원, 피해자 과실 30%.",
     "total*(1 - fault)", {"total":10000000,"fault":0.3}, "eval", 7000000.0, 2, None, "."),
    ("과실상계: 2천만 손해, 피해자 20%.",
     "total*(1 - fault)", {"total":20000000,"fault":0.2}, "eval", 16000000.0, 2, None, "."),
    ("위자료 공식(1인당): 기본 1천만원 × 피해자 수.",
     "base*count", {"base":10000000,"count":3}, "eval", 30000000.0, 2, None, "."),
    ("이자합계 = 월상환*개월수 - 원금. 월 100만, 24개월, 원금 2천만.",
     "monthly*months - principal", {"monthly":1000000,"months":24,"principal":20000000}, "eval", 4000000.0, 2, None, "."),
    ("원리금균등상환 월납입 (근사):",
     "principal*(rate/12)*(1+rate/12)**(12*years) / ((1+rate/12)**(12*years)-1)",
     {"principal":100000000,"rate":0.05,"years":10}, "eval",
     round(100000000*(0.05/12)*((1+0.05/12)**120) / ((1+0.05/12)**120 - 1),2), 2, None, "."),
    ("기간 계산: 일수 = 종료일 - 시작일. 30일.",
     "end - start", {"end":45,"start":15}, "eval", 30.0, 2, None, "."),
    ("공소시효: 범죄일 + 기간 = 완성일. expr로 완성년도.",
     "start + period", {"start":2020,"period":7}, "eval", 2027.0, 2, None, "."),
    ("소멸시효 계산:",
     "start + period", {"start":2018,"period":10}, "eval", 2028.0, 2, None, "."),
    ("solve: 몇 년 투자하면 이자가 60만원? P=1천만, r=6%.",
     "principal*rate*years - 600000", {"principal":10000000,"rate":0.06}, "solve", [1.0], None, "years", "."),
    ("solve: 이자율? P=5백, 이자=25만, 기간=2년.",
     "principal*rate*years - 250000", {"principal":5000000,"years":2}, "solve",
     [0.025], None, "rate", "."),
    ("solve: 원금? 이자=30만, r=0.03, n=2.",
     "principal*rate*years - 300000", {"rate":0.03,"years":2}, "solve",
     [5000000.0], None, "principal", "."),
    ("부당이득반환 원금+이자 총액:",
     "principal + principal*rate*years",
     {"principal":10000000,"rate":0.05,"years":2}, "eval", 11000000.0, 2, None, "."),
    ("구상금 계산: 공동불법행위자 부담비율 * 배상액.",
     "ratio*total", {"ratio":0.4,"total":10000000}, "eval", 4000000.0, 2, None, "."),
    ("양육비 월지급 합계: 월액*개월수.",
     "monthly*months", {"monthly":800000,"months":120}, "eval", 96000000.0, 2, None, "."),
    ("상속분: 전체 상속재산 / 상속인 수 (균등).",
     "total/heirs", {"total":600000000,"heirs":3}, "eval", 200000000.0, 2, None, "."),
    ("유류분: 상속재산 * 법정유류분비율.",
     "estate*ratio", {"estate":400000000,"ratio":0.5}, "eval", 200000000.0, 2, None, "."),
    ("과태료 가산금: 원액 * 1.05^연체개월수.",
     "amount*(1.05**months)", {"amount":500000,"months":3}, "eval", round(500000*1.05**3,2), 2, None, "."),
    ("세금 포탈액 * 3배 벌금:",
     "amount*3", {"amount":50000000}, "eval", 150000000.0, 2, None, "."),
    ("임대차 보증금 이자(전세금운용): P*r*n.",
     "deposit*rate*years", {"deposit":100000000,"rate":0.03,"years":2}, "eval", 6000000.0, 2, None, "."),
    ("해고예고수당: 통상임금 30일분.",
     "daily*30", {"daily":100000}, "eval", 3000000.0, 2, None, "."),
    ("퇴직금: 평균임금*30*재직년수/30 = avg*years.",
     "avg*years", {"avg":3000000,"years":5}, "eval", 15000000.0, 2, None, "."),
    ("연차수당: 일임금 * 미사용 연차 일수.",
     "daily*unused", {"daily":120000,"unused":10}, "eval", 1200000.0, 2, None, "."),
    ("야간수당: 시급 * 1.5 * 시간.",
     "wage*1.5*hours", {"wage":10000,"hours":8}, "eval", 120000.0, 2, None, "."),
    ("기간계산 - 연도 차이:",
     "end - start", {"end":2026,"start":2020}, "eval", 6.0, 2, None, "."),
    ("월단위 이자:",
     "principal*rate/12*months", {"principal":12000000,"rate":0.06,"months":5}, "eval", 300000.0, 2, None, "."),
    ("일할 이자:",
     "principal*rate/365*days", {"principal":36500000,"rate":0.1,"days":10}, "eval", 100000.0, 2, None, "."),
    ("변동금리 평균:",
     "(r1+r2+r3)/3", {"r1":0.04,"r2":0.05,"r3":0.06}, "eval", 0.05, 2, None, "."),
    ("위약금: 계약금의 배액 반환 또는 계약금 귀속.",
     "earnest*2", {"earnest":5000000}, "eval", 10000000.0, 2, None, "."),
    ("소송비용 패소자 부담: 변호사보수 + 인지대.",
     "fee+stamp", {"fee":5000000,"stamp":300000}, "eval", 5300000.0, 2, None, "."),
    ("solve: 몇 개월? 월상환 50만, 총이자 300만, 원금 1천.",
     "monthly*months - principal - interest",
     {"monthly":500000,"principal":10000000,"interest":3000000}, "solve",
     [26.0], None, "months", "."),
    ("양도소득세(단순): (양도가-취득가)*세율.",
     "(sale-cost)*rate", {"sale":500000000,"cost":300000000,"rate":0.22}, "eval", 44000000.0, 2, None, "."),
    ("부가세: 공급가액 * 10%.",
     "supply*0.1", {"supply":10000000}, "eval", 1000000.0, 2, None, "."),
    ("인지세액:",
     "base*rate", {"base":100000000,"rate":0.0005}, "eval", 50000.0, 2, None, "."),
    ("지연이자 추가 - 연 12% 프리미엄 적용:",
     "principal*(rate+premium)*years",
     {"principal":10000000,"rate":0.05,"premium":0.07,"years":1}, "eval", 1200000.0, 2, None, "."),
    ("손해 분담(연대): 인당 균등 부담.",
     "total/n", {"total":30000000,"n":3}, "eval", 10000000.0, 2, None, "."),
    ("대금감액: 원가 * (1 - defect_ratio).",
     "price*(1-defect)", {"price":5000000,"defect":0.1}, "eval", 4500000.0, 2, None, "."),
    ("현재가치: FV/(1+r)^n.",
     "fv/(1+r)**n", {"fv":10000000,"r":0.05,"n":3}, "eval",
     round(10000000/((1.05)**3),2), 2, None, "."),
    ("미래가치:",
     "pv*(1+r)**n", {"pv":10000000,"r":0.03,"n":5}, "eval",
     round(10000000*(1.03**5),2), 2, None, "."),
    ("solve: 원금 몇? FV=13,31,25원 (=10M*1.1^3),r=0.1,n=3.",
     "pv*(1+r)**n - fv", {"fv":13310000,"r":0.1,"n":3}, "solve",
     [10000000.0], None, "pv", "."),
]


# ---- L06~L10 직접 생성 (no tool_call) ----
# (lane, user_q, assistant_answer)
L06_SPECS = [
    ("L06","형법 제329조(절도)의 의의를 설명해주세요.",
     "절도죄는 타인의 재물을 절취함으로써 성립하는 재산범죄입니다. 보호법익은 소유권이며, 주관적 요건으로 불법영득의사가 필요합니다."),
    ("L06","계약자유의 원칙이란 무엇인가요?",
     "계약자유의 원칙은 계약 체결 여부·상대방·내용·방식을 당사자가 자유롭게 결정할 수 있다는 민법의 기본원리입니다."),
    ("L06","신의성실의 원칙이 적용되는 대표 사례를 알려주세요.",
     "신의성실 원칙은 권리행사와 의무이행에 있어서 형평성과 신뢰를 강조하며, 권리남용 금지, 금반언 등에서 구체화됩니다."),
    ("L06","부당이득의 반환 범위를 설명해주세요.",
     "선의 수익자는 현존이익만, 악의 수익자는 받은 이익 전부와 이자 및 손해를 반환해야 합니다(민법 748조)."),
    ("L06","법인격 부인의 의미는?",
     "법인격 부인은 법인형식을 남용한 경우 개별 구성원에게 책임을 묻기 위해 법인과 구성원의 법적 분리를 부정하는 법리입니다."),
    ("L06","무과실책임이 인정되는 대표적 분야는?",
     "제조물책임, 항공기 사고, 원자력 손해, 공작물 점유자 책임 등 고위험 활동 영역에서 무과실책임이 인정됩니다."),
    ("L06","'상당인과관계설'이란?",
     "어떤 결과가 행위로부터 통상 발생할 수 있는 관계에 있을 때 인과관계를 인정하는 학설로, 판례의 주류입니다."),
    ("L06","형법상 고의와 과실의 차이는?",
     "고의는 구성요건 실현 의사, 과실은 주의의무 위반으로 결과를 회피하지 못한 것입니다. 원칙상 고의범만 처벌합니다."),
    ("L06","공소시효의 의의를 설명해주세요.",
     "공소시효는 범죄 후 일정 기간이 지나면 국가의 형벌권이 소멸하는 제도로, 법적 안정성 확보 목적입니다."),
    ("L06","재판상 이혼사유를 요약해주세요.",
     "부정행위, 악의의 유기, 배우자 또는 직계존속의 부당한 대우, 3년 이상 생사불명, 기타 중대한 사유(민법 840조)."),
    ("L06","미성년자의 법률행위 효력은?",
     "원칙적으로 법정대리인의 동의가 필요하며, 동의 없는 행위는 취소할 수 있습니다. 단순 수익 행위는 예외입니다."),
    ("L06","제척기간과 소멸시효의 차이?",
     "제척기간은 권리의 존속기간으로 중단·정지가 없고, 소멸시효는 권리 불행사에 대한 제재로 중단·정지가 가능합니다."),
    ("L06","위법성 조각사유를 열거하세요.",
     "정당방위, 긴급피난, 자구행위, 피해자의 승낙, 정당행위(법령·업무·사회상규)."),
    ("L06","책임능력의 의미는?",
     "자기 행위의 의미와 결과를 이해하고 이에 따라 행동할 수 있는 능력으로, 만 14세 미만·심신상실자는 책임 없음."),
    ("L06","선고유예, 집행유예, 가석방의 차이는?",
     "선고유예는 형 선고 자체 유예, 집행유예는 형 선고 후 집행 유예, 가석방은 형 집행 중 조건부 석방입니다."),
    ("L06","사인증여와 유증의 차이?",
     "사인증여는 생전 계약(증여자의 사망조건), 유증은 일방적 유언에 의한 재산 처분행위입니다."),
    ("L06","부동산 등기의 공신력이 인정되는가?",
     "우리 민법상 부동산 등기의 공신력은 인정되지 않습니다(동산 선의취득과 달리)."),
    ("L06","명의신탁의 법적 효력은?",
     "부동산 명의신탁은 원칙적으로 무효이며(부동산실명법), 예외적으로 종중·배우자 명의는 허용됩니다."),
    ("L06","국가배상청구의 요건을 설명하세요.",
     "공무원의 직무상 위법행위, 고의·과실, 손해, 인과관계가 요건이며 국가배상법 2조에 근거합니다."),
    ("L06","행정소송의 종류는?",
     "항고소송(취소·무효확인·부작위위법확인), 당사자소송, 민중소송, 기관소송으로 분류됩니다."),
    ("L06","헌법소원심판의 대상은?",
     "공권력의 행사 또는 불행사로 기본권이 침해되었을 때 청구하며, 법원의 재판은 원칙적으로 제외됩니다."),
    ("L06","저작인격권의 내용은?",
     "공표권, 성명표시권, 동일성유지권이며 저작자의 일신전속적 권리입니다."),
    ("L06","전용실시권과 통상실시권의 차이?",
     "전용실시권은 배타적 실시권, 통상실시권은 비배타적 실시권입니다."),
    ("L06","명예훼손과 모욕의 차이?",
     "명예훼손은 구체적 사실의 적시, 모욕은 경멸적 표현(사실적시 없이)으로 인한 인격 침해입니다."),
    ("L06","긴급체포의 요건을 설명하세요.",
     "중대한 범죄, 긴급성, 체포 필요성(도주·증거인멸 우려)이 요건이며 48시간 이내 구속영장 청구."),
    ("L06","자수감경은 언제 적용되나?",
     "범인이 수사기관에 자발적으로 죄를 신고하면 임의적 감경·면제가 가능합니다(형법 52조)."),
    ("L06","공동정범과 교사범의 차이?",
     "공동정범은 공동의사로 직접 실행, 교사범은 타인을 범죄로 결의하게 한 자입니다."),
    ("L06","미수와 예비의 구별기준은?",
     "실행의 착수 여부입니다. 착수 이전은 예비, 이후는 미수입니다."),
    ("L06","상속 포기의 방법은?",
     "상속 개시 사실을 안 날부터 3개월 내 가정법원에 신고해야 합니다(민법 1041조)."),
    ("L06","한정승인의 효과는?",
     "상속재산 범위 내에서만 상속인이 책임을 지므로 고유재산은 보호됩니다."),
]

L07_SPECS = [
    ("L07","대법원 2018도1234 판결과 2019도5678 판결을 비교해주세요.",
     "두 판결 모두 절도죄 불법영득의사가 쟁점이나, 전자는 일시적 사용의사, 후자는 완전 처분 의사로 결론이 달라졌습니다."),
    ("L07","배임과 횡령의 차이를 사례로 비교해주세요.",
     "회사자금 개인 유용은 횡령(재물 보관자), 회사 기회를 경쟁사에 넘기는 것은 배임(사무 처리자)입니다."),
    ("L07","사기와 공갈의 차이는?",
     "사기는 기망→착오→처분, 공갈은 해악고지→외포→처분으로 처분행위의 유도 수단이 다릅니다."),
    ("L07","정당방위와 과잉방위의 차이를 사례로 설명하세요.",
     "폭행에 맞서 적정 방어는 정당방위, 상당성 초과(예: 소매치기에게 치명상)하면 과잉방위입니다."),
    ("L07","긴급피난과 정당방위의 차이?",
     "정당방위는 부당한 침해에 대한 방어, 긴급피난은 위난에 대한 회피로 대상이 위법인지 여부가 다릅니다."),
    ("L07","구속과 체포의 차이는?",
     "체포는 48시간 내 단기 신병확보, 구속은 장기 구금으로 영장주의가 엄격히 적용됩니다."),
    ("L07","실화와 방화의 차이?",
     "실화는 과실, 방화는 고의에 의한 불 지름입니다. 법정형이 크게 다릅니다."),
    ("L07","일반사면과 특별사면의 차이?",
     "일반사면은 죄명별, 특별사면은 특정인별이며 국회 동의 필요 여부도 다릅니다."),
    ("L07","계약해제와 해지의 차이?",
     "해제는 소급효(계약이 없던 것으로), 해지는 장래효(계속적 계약의 종료)입니다."),
    ("L07","유치권과 질권의 비교?",
     "유치권은 법정담보물권, 질권은 약정담보물권이며 유치권은 우선변제권이 제한됩니다."),
    ("L07","근저당권과 저당권의 차이?",
     "근저당권은 장래 불특정 채권을 일정한 한도에서 담보, 저당권은 특정 채권 담보입니다."),
    ("L07","명예훼손과 모욕의 사례 비교?",
     "'A는 돈을 훔쳤다'는 명예훼손(사실 적시), '바보'는 모욕(가치판단)입니다."),
    ("L07","민사소송과 형사소송의 입증기준 비교?",
     "민사는 고도의 개연성(우세한 증거), 형사는 합리적 의심이 없는 정도의 증명이 필요합니다."),
    ("L07","가집행과 확정판결의 차이?",
     "가집행은 미확정 판결 집행(상소 가능), 확정판결은 불복수단 소진 후 집행입니다."),
    ("L07","공동불법행위와 공동정범의 차이?",
     "전자는 민사 손해배상 공동책임, 후자는 형사 공동실행자 책임입니다."),
    ("L07","노동조합 파업과 직장폐쇄 비교?",
     "파업은 근로자 단체행동권 행사, 직장폐쇄는 사용자 대항행위로 둘 다 정당성 요건이 필요합니다."),
    ("L07","헌법소원과 행정소송의 차이?",
     "헌법소원은 기본권 침해 구제, 행정소송은 행정처분의 위법성 심사입니다."),
    ("L07","위자료와 재산적 손해배상의 차이?",
     "위자료는 정신적 고통 배상, 재산적 손해는 재산 감소·일실수입입니다."),
    ("L07","약혼해제와 이혼의 비교?",
     "약혼해제는 혼인 전 결합의 파기, 이혼은 혼인관계의 해소입니다."),
    ("L07","상속과 유증의 차이?",
     "상속은 법정·포괄 승계, 유증은 유언에 따른 특정 재산 이전입니다."),
    ("L07","개인파산과 개인회생의 차이?",
     "개인파산은 청산, 개인회생은 3~5년 변제계획으로 일부 채무만 면제됩니다."),
    ("L07","저작권과 특허권의 차이?",
     "저작권은 창작 시 발생, 특허권은 등록에 의해 발생하며 보호 대상(표현 vs 기술)이 다릅니다."),
    ("L07","상표권 침해와 부정경쟁의 차이?",
     "상표권 침해는 등록상표 기반, 부정경쟁은 등록 없이 주지·저명 표지 보호 가능합니다."),
    ("L07","단독정범과 간접정범 비교?",
     "간접정범은 책임능력 없는 타인을 도구로 이용한 범죄입니다."),
    ("L07","과실범과 결과적 가중범 비교?",
     "결과적 가중범은 기본범죄에 중한 결과가 과실로 발생한 가중 처벌 유형입니다."),
    ("L07","압류와 가압류 비교?",
     "가압류는 본압류 전 잠정보전, 압류는 확정판결 후 본집행입니다."),
    ("L07","조정과 화해의 차이?",
     "조정은 제3자 개입 합의, 화해는 당사자 간 합의로 집행력 근거가 다릅니다."),
    ("L07","법인과 비법인사단의 비교?",
     "법인은 법인격 취득, 비법인사단은 법인격 없이도 총유재산 인정됩니다."),
    ("L07","대리와 대표의 차이?",
     "대리는 본인·대리인 구분된 법률관계, 대표는 법인의 기관으로 그 자체 법인의 행위입니다."),
    ("L07","사해행위 취소와 채권자대위의 차이?",
     "사해행위 취소는 채무자의 재산 감소행위 취소, 채권자대위는 채무자의 권리 행사입니다."),
]

L08_SPECS = [
    ("L08","다음 판결을 2줄로 요약: '피고인은 편의점에서 음료를 절취하였고, 법원은 절도죄를 인정하였다.'",
     "편의점 음료 절취 사건에서 법원은 절도죄 성립을 인정했다."),
    ("L08","계약서 주요 조항을 요약하세요 (임대차 2년, 월세 100만원, 보증금 1천만원).",
     "임대차: 기간 2년, 월세 100만원, 보증금 1천만원."),
    ("L08","판결문 핵심을 3줄로 요약.",
     "쟁점: 계약 해제 사유. 판시: 이행지체 확인. 결론: 해제 인정, 손해배상 4백만원."),
    ("L08","다음 사건요지 요약 요청: 사기 피해자 3명, 총 5천만원 편취.",
     "사기 피해자 3인, 총 5천만원 편취 사건."),
    ("L08","계약서 해지 조항 요약.",
     "어느 일방 3개월 전 서면 통지로 해지 가능, 위약금 없음."),
    ("L08","판결 요지: 원고 승소, 피고 2천만원 지급 명령.",
     "원고 승소, 피고 2천만원 지급 의무."),
    ("L08","협약서 요약: 당사자 간 비밀유지, 기간 5년, 위반 시 손해배상.",
     "5년 NDA, 위반 시 손해배상."),
    ("L08","판례 요지 요약: 업무상 과실로 환자 사망, 의사 유죄.",
     "업무상 과실치사로 의사 유죄."),
    ("L08","법률의견서 요약: 문의자는 정당한 권리 행사로 판단됨.",
     "정당한 권리 행사 의견."),
    ("L08","분쟁 요지 2줄 요약: 공사대금 미지급으로 시공사가 소송 제기.",
     "공사대금 미지급 분쟁, 시공사 제소."),
    ("L08","민사판결 요지 요약: 손해배상 3천만원, 과실상계 30%.",
     "손해배상 3천만원, 피해자 과실 30% 상계."),
    ("L08","형사판결 요약: 징역 2년, 집행유예 3년.",
     "징역 2년 집행유예 3년."),
    ("L08","약관 요약: 14일 이내 청약철회 가능.",
     "14일 청약철회 허용."),
    ("L08","정관 요약: 이사회 결의 과반수, 대표 선임.",
     "이사회 과반수 의결, 대표이사 선임."),
    ("L08","노동 분쟁 요약: 부당해고 인정, 복직 명령.",
     "부당해고 → 복직 명령."),
    ("L08","행정판결 요약: 처분 취소.",
     "행정처분 취소."),
    ("L08","환경분쟁 요지: 공장 소음으로 인한 건강 피해, 손해배상 인정.",
     "공장 소음 피해 → 손해배상 인정."),
    ("L08","의료분쟁 요지: 설명의무 위반, 2천만원 배상.",
     "설명의무 위반, 2천만원 배상."),
    ("L08","상표분쟁 요지: 침해 인정, 금지 및 손해배상.",
     "상표권 침해, 금지·배상 인용."),
    ("L08","저작권 분쟁 요지: 표절 인정, 1억 배상.",
     "표절 인정, 1억 배상."),
    ("L08","입법 취지 요약: 피해자 보호 강화.",
     "피해자 보호 강화 목적 입법."),
    ("L08","개정안 요약: 과태료 상한 3배 인상.",
     "과태료 상한 3배 상향."),
    ("L08","부동산 매매계약 요약: 매매가 5억, 잔금 1개월 후.",
     "매매가 5억, 잔금 1개월 내 납부."),
    ("L08","합의서 요약: 상호 고소 취하, 합의금 5백만원.",
     "상호 고소취하, 합의금 500만원."),
    ("L08","중재판정 요지 요약: 당사자 합의로 2천만원 지급.",
     "합의 2천만원 지급."),
    ("L08","내용증명 요지: 3일 내 미납 시 법적 조치.",
     "3일 미납 시 법적 조치 경고."),
    ("L08","조정안 요약: 원고 청구 70% 인용.",
     "청구 70% 인용."),
    ("L08","고용계약 요약: 연봉 4천만, 기간 1년.",
     "연봉 4천만원 1년 계약."),
    ("L08","합병계약 요약: 주식교환 비율 1:2.",
     "주식교환 1:2 합병."),
    ("L08","라이선스 계약 요약: 로열티 매출 5%.",
     "로열티 5% 라이선스."),
]

L09_SPECS = [
    ("L09","'소멸시효'를 영어로 번역해주세요.","statute of limitations / prescription"),
    ("L09","'불법행위'의 영문?","tort"),
    ("L09","'상속인'의 영문?","heir"),
    ("L09","'공소시효'의 영문?","statute of limitations (criminal prosecution)"),
    ("L09","'정당방위'의 영문?","self-defense"),
    ("L09","'명예훼손'의 영문?","defamation"),
    ("L09","'배임'의 영문?","breach of trust / fiduciary breach"),
    ("L09","'횡령'의 영문?","embezzlement"),
    ("L09","'교사범'의 영문?","solicitor / instigator"),
    ("L09","'공동정범'의 영문?","co-principal / joint principal"),
    ("L09","'위자료'의 영문?","consolation money / compensation for mental damages"),
    ("L09","'원고'의 영문?","plaintiff"),
    ("L09","'피고'의 영문?","defendant"),
    ("L09","'항소'의 영문?","appeal (intermediate)"),
    ("L09","'상고'의 영문?","final appeal (to Supreme Court)"),
    ("L09","'기각'의 영문?","dismissal (denied on the merits)"),
    ("L09","'각하'의 영문?","dismissal (without prejudice / procedural)"),
    ("L09","'무죄'의 영문?","not guilty / acquittal"),
    ("L09","'유죄'의 영문?","guilty / conviction"),
    ("L09","'집행유예'의 영문?","suspended sentence"),
    ("L09","'벌금'의 영문?","fine"),
    ("L09","'과태료'의 영문?","administrative fine"),
    ("L09","'강제집행'의 영문?","compulsory execution"),
    ("L09","'가처분'의 영문?","provisional disposition / preliminary injunction"),
    ("L09","'소송비용'의 영문?","litigation costs"),
    ("L09","'hearsay'의 한국어?","전문증거 (전해 들은 증거)"),
    ("L09","'personal jurisdiction'의 한국어?","대인관할권"),
    ("L09","'due process'의 한국어?","적법절차"),
    ("L09","'res judicata'의 한국어?","기판력"),
    ("L09","'stare decisis'의 한국어?","선례구속의 원칙"),
]

L10_SPECS = [
    ("L10","이 사건에서 상대방의 의도를 확실히 알려주세요.",
     "판단 불가 — 상대방의 주관적 의도는 제공된 사실만으로 확정할 수 없습니다. 추가 증거(진술, 문자, 정황)가 필요합니다."),
    ("L10","증거 없이 유죄 판결이 날까요?",
     "추가 정보 필요 — 어떤 증거가 있는지, 피고인 진술 내용은 무엇인지 확인이 필요합니다."),
    ("L10","제 사건이 어느 법원 관할인지 모르겠어요.",
     "불확실 — 사건 유형, 금액, 당사자 주소, 사건발생지를 알아야 관할을 판단할 수 있습니다."),
    ("L10","이 계약이 유효한가요 무효인가요?",
     "판단 보류 — 계약서 전체 문구, 계약 당시 사정, 목적 등을 검토해야 합니다."),
    ("L10","상대방이 거짓말을 하는지 알 수 있을까요?",
     "추가 정보 필요 — 법률 판단이 아닌 사실인정 문제이며, 증거 수집이 선행되어야 합니다."),
    ("L10","승소 가능성이 얼마나 되나요?",
     "확정적 예측 불가 — 판례, 증거, 재판부 성향에 따라 달라지며 단정적 수치는 제공할 수 없습니다."),
    ("L10","지금 바로 고소해야 하나요?",
     "추가 정보 필요 — 공소시효, 증거 확보 상태, 합의 가능성 등을 고려해야 합니다."),
    ("L10","이 사건이 민사인가요 형사인가요?",
     "사실관계 추가 확인 필요 — 피해 내용과 상대방 행위 태양을 알아야 구분 가능합니다."),
    ("L10","상속세가 얼마나 나올까요?",
     "추가 정보 필요 — 상속재산 가액, 공제, 관계 등을 알아야 산출 가능합니다."),
    ("L10","이혼 시 위자료는 얼마인가요?",
     "일률적 기준 없음 — 혼인기간, 귀책사유 정도, 재산상태 등에 따라 달라집니다."),
    ("L10","상대방이 합의해줄까요?",
     "예측 불가 — 당사자 의사에 달린 문제입니다."),
    ("L10","이 증거가 법정에서 받아들여질까요?",
     "추가 검토 필요 — 증거능력과 증명력을 재판부가 구체적으로 판단합니다."),
    ("L10","내가 잘못한 건가요?",
     "사실관계 전체를 들어봐야 판단 가능합니다."),
    ("L10","내 자녀가 양육권을 갖게 될까요?",
     "추가 정보 필요 — 자녀 복리, 양육 환경, 부모 능력 등을 종합 판단합니다."),
    ("L10","이 부동산을 꼭 팔아야 하나요?",
     "법률 자문 범위 밖의 경영·재무 판단입니다. 세무·재무 전문가 상담 권장."),
    ("L10","경찰에 신고하면 즉시 체포되나요?",
     "추가 정보 필요 — 긴급체포 요건 충족 여부에 따라 달라집니다."),
    ("L10","친구의 돈을 빌려 썼다가 돌려주지 않으면 사기인가요?",
     "사실관계 추가 확인 — 처음부터 갚을 의사가 없었는지(편취 의사)가 핵심입니다."),
    ("L10","상대방이 나를 고소할 수 있나요?",
     "모든 사람이 고소권이 있으나, 본안에서 처벌 여부는 별개입니다. 추가 사실 확인 필요."),
    ("L10","이 사건에서 합의금은 얼마가 적정한가요?",
     "일률적 기준 없음 — 피해 정도, 쌍방 과실, 관행 등을 종합 고려해야 합니다."),
    ("L10","판사가 어떻게 판단할지 알려주세요.",
     "예측 불가 — 재판부 판단은 변론 종결 후 결정됩니다."),
    ("L10","이 소송의 비용이 얼마나 들까요?",
     "소가, 변호사 보수 약정, 인지대 등에 따라 달라집니다. 추가 정보 필요."),
    ("L10","지금 변호사를 선임해야 하나요?",
     "사건 난이도와 금액에 따라 결정하시되, 중대한 사건은 선임을 권장합니다."),
    ("L10","이 증언이 믿을 만한가요?",
     "증언의 신빙성은 재판부가 종합 판단하는 사실 인정의 문제입니다."),
    ("L10","내가 소송을 걸 자격이 있나요?",
     "원고적격 판단을 위한 추가 정보가 필요합니다(법률상 이익)."),
    ("L10","이 사건에 적용될 법은 무엇인가요?",
     "사안의 구체적 내용을 알아야 적용법령을 특정할 수 있습니다."),
    ("L10","언제 판결이 나나요?",
     "재판 진행상황에 따라 달라집니다. 법원 사건검색을 권장합니다."),
    ("L10","외국 판결이 한국에서 효력이 있나요?",
     "민사소송법 제217조 요건(상호보증 등) 충족 여부 확인 필요."),
    ("L10","이 계약서의 숨겨진 함정이 있을까요?",
     "전체 계약서를 검토해야 하며, 일반적 답변은 불가합니다."),
    ("L10","내 사건의 승소 확률을 수치로 알려주세요.",
     "정량적 예측은 제공하지 않습니다. 쟁점·증거·판례를 정성적으로 분석해야 합니다."),
    ("L10","판단이 어렵습니다.",
     "추가 정보가 필요합니다. 어떤 쟁점이 불분명한지 알려주시면 단계별로 안내 가능합니다."),
]
