"""Validate generated SFT/DPO data; write reports/data_quality.md.

Metrics:
  - per-Lane count
  - roundtrip pass rate (tool-bearing lanes only)
  - schema validation rate
  - LegalBench CSV status (data/legalbench/)
  - KLAC schema status
"""
from __future__ import annotations
import json
import sys
from pathlib import Path
from collections import Counter

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from solver.validator import roundtrip, validate_schema, extract_from_messages

SFT = ROOT / "data" / "sft_merged.jsonl"
DPO = ROOT / "data" / "dpo_pairs.jsonl"
LEGALBENCH_DIR = ROOT / "data" / "legalbench"
REPORT = ROOT / "reports" / "data_quality.md"


def load_jsonl(p):
    with p.open(encoding="utf-8") as f:
        for line in f:
            if line.strip():
                yield json.loads(line)


def audit_sft():
    total = 0
    lane_counter = Counter()
    roundtrip_pass = 0
    roundtrip_total = 0
    schema_pass = 0
    schema_total = 0
    sample_failures = []
    for s in load_jsonl(SFT):
        total += 1
        lane_counter[s["lane"]] += 1
        lane, tc, tr = extract_from_messages(s["messages"])
        if tc is None:
            continue
        roundtrip_total += 1
        if roundtrip(s):
            roundtrip_pass += 1
        else:
            if len(sample_failures) < 5:
                sample_failures.append(s["lane"])
        schema_total += 1
        if validate_schema(tc, lane):
            schema_pass += 1
    return {
        "total": total,
        "lane": dict(lane_counter),
        "roundtrip_pass": roundtrip_pass,
        "roundtrip_total": roundtrip_total,
        "schema_pass": schema_pass,
        "schema_total": schema_total,
        "failure_lanes": sample_failures,
    }


def audit_dpo():
    total = 0
    chosen_pass = 0
    rejected_fail = 0
    for pair in load_jsonl(DPO):
        total += 1
        if roundtrip(pair["chosen"]):
            chosen_pass += 1
        if not roundtrip(pair["rejected"]):
            rejected_fail += 1
    return {"total": total, "chosen_pass": chosen_pass, "rejected_fail": rejected_fail}


def legalbench_status():
    entries = []
    if not LEGALBENCH_DIR.exists():
        return entries
    for p in sorted(LEGALBENCH_DIR.glob("*.csv")):
        try:
            n = sum(1 for _ in p.open(encoding="utf-8")) - 1
        except Exception:
            n = -1
        entries.append((p.name, n))
    return entries


def read_klac_status():
    f = ROOT / "data" / "klac_status.json"
    if f.exists():
        return json.loads(f.read_text(encoding="utf-8"))
    return None


def write_report(sft, dpo, lb, klac):
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    rt_rate = 100.0 * sft["roundtrip_pass"] / max(1, sft["roundtrip_total"])
    sc_rate = 100.0 * sft["schema_pass"] / max(1, sft["schema_total"])

    lines = [
        "# Data Quality Report",
        "",
        f"Generated by `scripts/validate_data.py`.",
        "",
        "## SFT corpus (`data/sft_merged.jsonl`)",
        "",
        f"- Total samples: **{sft['total']}**",
        f"- Tool-bearing samples: {sft['roundtrip_total']}",
        f"- **Roundtrip pass rate: {rt_rate:.2f}%** ({sft['roundtrip_pass']}/{sft['roundtrip_total']})",
        f"- Schema validation rate: {sc_rate:.2f}% ({sft['schema_pass']}/{sft['schema_total']})",
        "",
        "### Lane distribution",
        "",
        "| Lane | Count |",
        "|------|-------|",
    ]
    for lane, n in sorted(sft["lane"].items()):
        lines.append(f"| {lane} | {n} |")

    lines += [
        "",
        "## DPO pairs (`data/dpo_pairs.jsonl`)",
        "",
        f"- Total pairs: {dpo['total']}",
        f"- chosen roundtrip pass: {dpo['chosen_pass']} ({100*dpo['chosen_pass']/max(1,dpo['total']):.1f}%)",
        f"- rejected roundtrip fail: {dpo['rejected_fail']} ({100*dpo['rejected_fail']/max(1,dpo['total']):.1f}%)",
        "",
        "## LegalBench CSV preparation (`data/legalbench/`)",
        "",
    ]
    if lb:
        lines += ["| File | Rows |", "|------|------|"]
        for name, n in lb:
            lines.append(f"| {name} | {n} |")
    else:
        lines.append("_No CSVs prepared (HF fetch may have failed — see `data/legalbench_status.json`)._")

    lb_status_file = ROOT / "data" / "legalbench_status.json"
    if lb_status_file.exists():
        lines += ["", "```json", lb_status_file.read_text(encoding="utf-8"), "```"]

    lines += ["", "## KLAC (`jihye-moon/klac_legal_aid_counseling`)", ""]
    if klac:
        lines.append("```json")
        lines.append(json.dumps(klac, ensure_ascii=False, indent=2))
        lines.append("```")
    else:
        lines.append("_Not probed yet (see `scripts/fetch_datasets.py`)._")

    lines += [
        "",
        "## Targets & gating",
        "",
        "- Director target: roundtrip pass ≥ 85%.",
        f"- Current: **{rt_rate:.2f}%** — " + ("PASS" if rt_rate >= 85.0 else "FAIL, revise pipeline"),
        "",
        "## Notes",
        "",
        "- All L01 samples use `mode=and` by default unless explicitly marked `or`.",
        "- L04 uses a custom propositional parser (`=>`, `<=>`, `and/or/not`, `&&/||/!`).",
        "- L05 `solve` samples preserve the expected target (not randomised).",
        "- Direct-generation lanes (L06–L10) bypass solver — they always 'pass' roundtrip because no tool_call is emitted.",
    ]
    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Report written: {REPORT}")
    print(f"Roundtrip: {rt_rate:.2f}%")


def main():
    sft = audit_sft()
    dpo = audit_dpo()
    lb = legalbench_status()
    klac = read_klac_status()
    write_report(sft, dpo, lb, klac)


if __name__ == "__main__":
    main()
